### ISSUE TITLE
Inconsistent project documentation?

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#1504]
The prjxray sphinx docs should be identical when viewed;
 - Directly via prjxray
 - When part of the symbiflow documentation

The documentation when viewed at https://symbiflow.readthedocs.io/projects/prjxray/en/latest/# has a fairly short list under items;

![Screenshot from 2020-11-24 09-45-46](https://user-images.githubusercontent.com/21212/100132175-e54d6400-2e39-11eb-8762-5538bebb0a00.png)

Yet, when you view the documentation at https://symbiflow.readthedocs.io/en/latest/ you get a much longer output;

![Screenshot from 2020-11-24 09-46-24](https://user-images.githubusercontent.com/21212/100132222-f4ccad00-2e39-11eb-97d1-41482b5cdebc.png)

**Comment by mithro** [comment]
@tcal-x - This is what you discovered?

**Comment by rw1nkler** [comment]
Probably this is due to missing links in the documentation when building on RTD:
https://github.com/SymbiFlow/symbiflow-docs/blob/master/source/conf.py#L348

I will check that

**Comment by tcal-x** [comment]
@mithro It was more that on Prjxray docs, after "fuzzers", "minitests", "tools", then my new "Guide.." appeared.    On Symbiflow docs, my new "Guide..." doesn't appear at the same point.    So perhaps I need to find another file in which to add a link to the new guide.

**Comment by tcal-x** [comment]
To be clear, this issue is unrelated to my original issue, which is that the link for "Guide to adding a new device to an existing family" is missing from the Symbiflow version of the docs.   The underlying reason for my issue may be https://github.com/SymbiFlow/symbiflow-docs/issues/395 , which blocks the prjxray submodule update on symbiflow-docs.

Looking at _this_ PR, now prjxray doc pages have the same section repeated at different points in the hierarchy -- is this intended?   Specifically, https://symbiflow--1505.org.readthedocs.build/projects/prjxray/en/1505/db_dev_process/readme.html is linked both from under "Getting Started" and also from under "Database Development Process".

However, without this PR (that is, on the current prjxray docs "latest"), this material  ("Quickstart Guide", "C++ Development", "Process", ...) doesn't appear _anywhere_ that I can see.

So we are jumping from not having the material at all, to having it appear at two places in the hierarchy.   I will need to look at it more, and maybe look at the history, to understand what is going on.

**Comment by tcal-x** [comment]
Note: the section repetition (the same material appearing at two places in the hierarchy) is what is currently on the Symbiflow version, so it is not something new introduced in this PR.    This PR just makes the Prjxray match the existing Symbiflow organization, which has the duplication.
