### ISSUE TITLE
review htmlgen

### ISSUE THREAD

**Issue by mcmasterg** [SymbiFlow/prjxray#173]
Some HTML sections like BRAM have changed after recent commits (think they are broken?). Review after BRAM DB commits to get them into a reasonable state

This will probably start a larger conversation about what a segment means now, and how we should display things. For example, we may want to move to tile only, and drop the original notation of segments (which I think only htmlgen uses right now?)

**Comment by mithro** [comment]
Looks like it still broken?

![image](https://user-images.githubusercontent.com/21212/47465455-f4b4db80-d7a1-11e8-9e0f-9dbf950fff3b.png)

**Comment by JohnDMcMaster** [comment]
@tmichalak is looking into this

**Comment by tmichalak** [comment]
For the record, despite the changes the BRAM_L is still presented in four columns with frames 5 to 25 in each column hidden. This means that it's still different from the visualization on the left shown in the image posted by @mithro in this thread. However, from looking at the code, this seems intentional.

**Comment by tmichalak** [comment]
It seems the original issue was fixed long time ago. I am closing it for now, we can open new htmlgen related issues if needed.
