### ISSUE TITLE
Generate `.json` output from the `.yaml` files

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/prjxray#83]
Currently to understand the prjxray database you need to be able to parse both `.json` and `.yaml` file formats.

yaml has a canonical format way to be transformed into json -- so we should provide "jsonfied" version of the yaml files side-by-side with the yaml files.

This also makes it easier to use the data directly from javascript.

**Comment by mcmasterg** [comment]
If this is something we care about, wouldn't we be better off standardizing on json? What is the main advantage of yaml over json?

**Comment by mithro** [comment]
That is what I'm suggesting, that we have everything in json format.

**Comment by mcmasterg** [comment]
You are proposing side by side. I'm proposing eliminating YAML

**Comment by kc8apf** [comment]
I wrote the part files in YAML because I was planning to use the node aliasing feature.  It also happens that I found a decent YAML library for c++ before I found a decent JSON library.  Given other discussions about removing segments as a concept, needing to describe logical blocks with an N:M mapping onto tiles, etc, I'd like us to settle on a format that resolves those issues.

**Comment by mithro** [comment]
This now happens.
